//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorios
    {
        public int id_Accesorios { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
        public string url_foto { get; set; }
        public int Categoria_Id { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
